var data={
	"logo": {
		"url": "https:\/\/www.baidu.com\/"
	},
	"weather": {
		"update_time": "2021-10-13 17:33",
		"publish_time": "2021-10-13 17:31",
		"temperature": "23",
		"wind_power": "1级",
		"wind_direction": "北风",
		"wind_power_num": "1",
		"site": "mlogcn",
		"humidity": "40.0",
		"weather": "多云",
		"precipitation_type": "无降雨和降雪",
		"wind_direction_num": "8",
		"precipitation": "0.0",
		"weather_day": "晴",
		"weather_night": "晴",
		"wind_direction_day": "北风",
		"wind_power_day": "<3级",
		"wind_direction_night": "西北风",
		"wind_power_night": "<3级"
	},
	"position": {
		"city": "郑州",
		"country": "中国"
	},
	"ps_pm25": {
		"level": "良",
		"ps_pm25": "54"
	},
	"feature": {
		"humidity": "40.0",
		"wind": "北风1级",
		"sunriseTime": "06:29",
		"sunsetTime": "17:54",
		"ultraviolet": "中等"
	},
	"base": {
		"dateShort": "10月13日",
		"date": "2021-10-13",
		"weekday": "周四",
		"lunar": "九月初八"
	},
	"long_day_forecast": {
		"info": [{
			"weather_day": "晴",
			"wind_direction_night": "西北风",
			"temperature_day": "23",
			"wind_direction_day": "北风",
			"weather_night": "晴",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-13",
			"sunsetTime": "17:54",
			"temperature_night": "12",
			"sunriseTime": "06:29",
			"pm25": {
				"listQuality": {
					"listKey": "2",
					"listValue": "良",
					"listAqiVal": "57",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-13"
			},
			"humidity": {
				"tip": "湿度",
				"text": "40.0"
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "西北风",
			"temperature_day": "21",
			"wind_direction_day": "北风",
			"weather_night": "小雨",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-14",
			"sunsetTime": "17:53",
			"temperature_night": "14",
			"sunriseTime": "06:30",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "34",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-14"
			}
		}, {
			"weather_day": "小雨",
			"wind_direction_night": "北风",
			"temperature_day": "18",
			"wind_direction_day": "北风",
			"weather_night": "小雨",
			"wind_power_day": "3-4级",
			"wind_power_night": "4-5级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-15",
			"sunsetTime": "17:52",
			"temperature_night": "12",
			"sunriseTime": "06:30",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "31",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-15"
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "东北风",
			"temperature_day": "14",
			"wind_direction_day": "东北风",
			"weather_night": "晴",
			"wind_power_day": "4-5级",
			"wind_power_night": "<3级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-16",
			"sunsetTime": "17:50",
			"temperature_night": "4",
			"sunriseTime": "06:31",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "37",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-16"
			}
		}, {
			"weather_day": "晴",
			"wind_direction_night": "南风",
			"temperature_day": "13",
			"wind_direction_day": "南风",
			"weather_night": "阴",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-17",
			"sunsetTime": "17:49",
			"temperature_night": "6",
			"sunriseTime": "06:32",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "35",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-17"
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "东北风",
			"temperature_day": "18",
			"wind_direction_day": "西南风",
			"weather_night": "阴",
			"wind_power_day": "<3级",
			"wind_power_night": "3-4级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-18",
			"sunsetTime": "17:48",
			"temperature_night": "8",
			"sunriseTime": "06:33",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "49",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-18"
			}
		}, {
			"weather_day": "阴",
			"wind_direction_night": "北风",
			"temperature_day": "14",
			"wind_direction_day": "东北风",
			"weather_night": "阴",
			"wind_power_day": "3-4级",
			"wind_power_night": "<3级",
			"weather_night_for_beijing": "",
			"weather_day_for_beijing": "",
			"date": "2021-10-19",
			"sunsetTime": "17:47",
			"temperature_night": "8",
			"sunriseTime": "06:34",
			"pm25": {
				"listQuality": {
					"listKey": "1",
					"listValue": "优",
					"listAqiVal": "43",
					"site": "mlogcn"
				},
				"listTitle": "2021-10-19"
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "南风",
			"temperature_day": "17",
			"wind_direction_day": "西南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-20",
			"sunsetTime": "17:45",
			"temperature_night": "9",
			"sunriseTime": "06:35",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "南风",
			"temperature_day": "17",
			"wind_direction_day": "东南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-21",
			"sunsetTime": "17:44",
			"temperature_night": "9",
			"sunriseTime": "06:36",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "西南风",
			"temperature_day": "20",
			"wind_direction_day": "南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-22",
			"sunsetTime": "17:43",
			"temperature_night": "8",
			"sunriseTime": "06:36",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "南风",
			"temperature_day": "19",
			"wind_direction_day": "南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-23",
			"sunsetTime": "17:42",
			"temperature_night": "8",
			"sunriseTime": "06:37",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "南风",
			"temperature_day": "19",
			"wind_direction_day": "西南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-24",
			"sunsetTime": "17:41",
			"temperature_night": "10",
			"sunriseTime": "06:38",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "西南风",
			"temperature_day": "19",
			"wind_direction_day": "西北风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-25",
			"sunsetTime": "17:40",
			"temperature_night": "10",
			"sunriseTime": "06:39",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "多云",
			"wind_direction_night": "南风",
			"temperature_day": "20",
			"wind_direction_day": "南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-26",
			"sunsetTime": "17:39",
			"temperature_night": "11",
			"sunriseTime": "06:40",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"weather_day": "阴",
			"wind_direction_night": "南风",
			"temperature_day": "19",
			"wind_direction_day": "南风",
			"weather_night": "多云",
			"wind_power_day": "<3级",
			"wind_power_night": "<3级",
			"date": "2021-10-27",
			"sunsetTime": "17:37",
			"temperature_night": "10",
			"sunriseTime": "06:41",
			"pm25": {
				"listTitle": "",
				"listQuality": {
					"listKey": "",
					"listValue": ""
				}
			}
		}, {
			"date": "2021-10-28",
			"weather_day": "多云",
			"weather_night": "晴",
			"temperature_night": "9",
			"temperature_day": "18"
		}, {
			"date": "2021-10-29",
			"weather_day": "晴",
			"weather_night": "多云",
			"temperature_night": "10",
			"temperature_day": "20"
		}, {
			"date": "2021-10-30",
			"weather_day": "阴",
			"weather_night": "多云",
			"temperature_night": "9",
			"temperature_day": "16"
		}, {
			"date": "2021-10-31",
			"weather_day": "小雨",
			"weather_night": "小雨",
			"temperature_night": "11",
			"temperature_day": "15"
		}, {
			"date": "2021-11-01",
			"weather_day": "阴",
			"weather_night": "小雨",
			"temperature_night": "12",
			"temperature_day": "16"
		}, {
			"date": "2021-11-02",
			"weather_day": "多云",
			"weather_night": "多云",
			"temperature_night": "10",
			"temperature_day": "19"
		}, {
			"date": "2021-11-03",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "7",
			"temperature_day": "18"
		}, {
			"date": "2021-11-04",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "8",
			"temperature_day": "18"
		}, {
			"date": "2021-11-05",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "5",
			"temperature_day": "16"
		}, {
			"date": "2021-11-06",
			"weather_day": "多云",
			"weather_night": "多云",
			"temperature_night": "6",
			"temperature_day": "14"
		}, {
			"date": "2021-11-07",
			"weather_day": "晴",
			"weather_night": "多云",
			"temperature_night": "6",
			"temperature_day": "14"
		}, {
			"date": "2021-11-08",
			"weather_day": "阴",
			"weather_night": "多云",
			"temperature_night": "6",
			"temperature_day": "14"
		}, {
			"date": "2021-11-09",
			"weather_day": "阴",
			"weather_night": "阴",
			"temperature_night": "7",
			"temperature_day": "15"
		}, {
			"date": "2021-11-10",
			"weather_day": "多云",
			"weather_night": "小雨",
			"temperature_night": "9",
			"temperature_day": "16"
		}, {
			"date": "2021-11-11",
			"weather_day": "小雨",
			"weather_night": "晴",
			"temperature_night": "9",
			"temperature_day": "15"
		}, {
			"date": "2021-11-12",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "7",
			"temperature_day": "17"
		}, {
			"date": "2021-11-13",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "8",
			"temperature_day": "17"
		}, {
			"date": "2021-11-14",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "5",
			"temperature_day": "15"
		}, {
			"date": "2021-11-15",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "4",
			"temperature_day": "15"
		}, {
			"date": "2021-11-16",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "1",
			"temperature_day": "10"
		}, {
			"date": "2021-11-17",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "3",
			"temperature_day": "11"
		}, {
			"date": "2021-11-18",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "4",
			"temperature_day": "13"
		}, {
			"date": "2021-11-19",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "5",
			"temperature_day": "15"
		}, {
			"date": "2021-11-20",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "7",
			"temperature_day": "15"
		}, {
			"date": "2021-11-21",
			"weather_day": "晴",
			"weather_night": "晴",
			"temperature_night": "8",
			"temperature_day": "17"
		}],
		"update_time": "2021-10-13 11:51",
		"publish_time": "2021-10-13 11:41",
		"pm25_update_time": "2021-10-13 11:51",
		"pm25_publish_time": "2021-10-13 11:41",
		"weather_publish_time": "2021-10-13 11:41",
		"weather_update_time": "2021-10-13 11:51",
		"info#num#baidu": 7,
		"days": "40"
	}
}